apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
  labels:
    app: story
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: kodega2016/kube_volume
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /story
              port: 3000
            periodSeconds: 3
            initialDelaySeconds: 3
          volumeMounts:
            - name: stories-data
              mountPath: /app/story
      volumes:
        - name: stories-data
          persistentVolumeClaim:
            claimName: story-persistent-volume-claim
      # hostPath:
      #   path: /data
      #   type: DirectoryOrCreate
      # emptyDir: {}
