apiVersion: v1
kind: Service
metadata:
  name: story-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: story
  ports:
    - name: story
      protocol: TCP
      port: 80
      targetPort: 3000
