apiVersion: v1
kind: Pod
metadata:
  name: story-pod
  labels:
    app: story
spec:
  containers:
    - name: story
      image: kodega2016/kube_volume
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: story-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: story
  ports:
    - name: story
      protocol: TCP
      port: 80
      targetPort: 3000
