apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-persistent-volume-claim
spec:
  volumeName: story-persistent-volume
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
